version: "3.7"
volumes:
  metaxdata:
  qvaindata:
  elasticsearchdata:
  idadata:
  code-qvain:
  code-metax:
  code-download:
  code-etsin:
  install-download:
  install-qvain:
  install-metax:
  user-metax:
  user-qvain:
  user-etsin:
  code-simplesaml:
  code-fairdata:
  code-ida:
  matomo-db:
  matomo:

services:
  simplesaml.csc.local:
    image: simplesaml:1
    build:
      context: ./simplesaml
    domainname: csc.local
    hostname: simplesaml
    privileged: true
    ports:
      - "2230:22"
      - "${SAML_PORT_HTTPS:-2443}:443"
      - "${SAML_PORT_HTTP:-2080}:80"
    depends_on:
      - cscdevbase
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-simplesaml:/code
    cap_add:
      - ALL

  auth.csc.local:
    image: oryd/hydra:latest
    domainname: csc.local
    hostname: auth-consent
    ports:
      - "${AUTH_PUBLIC_PORT:-4444}:4444" # Public port
      - "${AUTH_ADMIN_PORT:-4445}:4445" # Admin port
      - "${AUTH_TOKEN_PORT:-5555}:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://auth.csc.local:${AUTH_PUBLIC_PORT:-4444}
      - URLS_CONSENT=http://auth-consent.csc.local:${AUTH_CONSENT_PORT:-3000}/consent
      - URLS_LOGIN=http://auth-consent.csc.local:${AUTH_CONSENT_PORT:-3000}/login
      - URLS_LOGOUT=http://auth-consent.csc.local:${AUTH_CONSENT_PORT:-3000}/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
    restart: unless-stopped

  auth-consent.csc.local:
    image: auth-consent:1
    domainname: csc.local
    hostname: auth-consent
    build:
      context: ./hydra-login-consent-node
    environment:
      - HYDRA_ADMIN_URL=http://auth.csc.local:${AUTH_ADMIN_PORT:-4445}
    ports:
      - "${AUTH_CONSENT_PORT:-3000}:3000"
    restart: unless-stopped

  cscdevbase:
    image: cscdevbase:1
    build:
      context: ./cscdevbase
      args:
        ssh_key: "${SSH_KEY:-id_rsa.pub}"
        root_password: "${ROOT_PASSWORD:-changeme}"
    privileged: true
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
    cap_add:
      - ALL

  ida-postgres.csc.local:
    image: postgres:9
    domainname: csc.local
    hostname: ida-postgres
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: nextcloud
      PGDATA: /data/pg96/nextcloud
    volumes:
      - idadata:/data/

  metax-postgres.csc.local:
    image: postgres:9
    domainname: csc.local
    hostname: metax-postgres
    environment:
      POSTGRES_USER: metax_db_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: metax_db
      PGDATA: /data/pg96/metax
    volumes:
      - metaxdata:/data/

  qvain-postgres.csc.local:
    image: postgres:9
    domainname: csc.local
    hostname: qvain-postgres
    environment:
      POSTGRES_USER: qvain
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: qvaindb
      PGDATA: /data/pg96/QVAIN_prod
    volumes:
      - qvaindata:/data/

  rabbitmq.csc.local:
    image: rabbitmq:3.7
    domainname: csc.local
    hostname: rabbitmq
    environment:
      RABBITMQ_NODENAME: metax@rabbitmq.csc.local
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_ERLANG_COOKIE: supersecret
      RABBITMQ_DEFAULT_USER: metax-user
      RABBITMQ_DEFAULT_PASS: changeme
      RABBITMQ_DEFAULT_VHOST: metax

  rabbitmq-ida.csc.local:
    image: rabbitmq:3.8-management
    domainname: csc.local
    hostname: rabbitmq-ida
    environment:
      RABBITMQ_NODENAME: ida@rabbitmq-ida.csc.local
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_ERLANG_COOKIE: supersecret
      RABBITMQ_DEFAULT_USER: ida-admin
      RABBITMQ_DEFAULT_PASS: changeme
      RABBITMQ_DEFAULT_VHOST: ida-vhost

  elasticsearch.csc.local:
    image: elasticsearch:5.6.11
    domainname: csc.local
    hostname: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data

  download.csc.local:
    image: fairdownload:1
    domainname: csc.local
    hostname: download
    build:
      context: ./download
      args:
        ssh_key: "${SSH_KEY:-id_rsa.pub}"
        root_password: "${ROOT_PASSWORD:-changeme}"
        metax_secrets: service/metax.properties.template
    privileged: true
    ports:
      - "${DOWNLOAD_PORT:-8433}:8433"
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-download:/build
      - install-download:/opt/login-download
    cap_add:
      - ALL

  metax.csc.local:
    image: metax:1
    domainname: csc.local
    hostname: metax
    build:
      context: ./metax
      args:
        metax_password: "${METAX_PASSWORD:-changeme}"
        metax_branch: "${METAX_BRANCH:-test}"
    privileged: true
    ports:
      - "${METAX_PORT_HTTPS:-1443}:443"
      - "${METAX_PORT_HTTP:-1080}:80"
    depends_on:
      - cscdevbase
      - rabbitmq.csc.local
      - metax-postgres.csc.local
      - elasticsearch.csc.local
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-metax:/code
      - install-metax:/opt/fairdata
      - user-metax:/home/metax-user
    cap_add:
      - ALL

  qvain.csc.local:
    image: qvain:1
    domainname: csc.local
    hostname: qvain
    build:
      context: ./qvain
      args:
        qvain_password: "${QVAIN_PASSWORD:-changeme}"
        qvain_js_branch: "${QVAIN_JS_BRANCH:-next}"
        qvain_api_branch: "${QVAIN_API_BRANCH:-next}"
    privileged: true
    depends_on:
      - cscdevbase
      - qvain-postgres.csc.local
      - auth.csc.local
      - auth-consent.csc.local
      - matomo.csc.local
    ports:
      - "${QVAIN_PORT_HTTPS:-443}:443"
      - "${QVAIN_PORT_HTTP:-80}:80"
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-qvain:/code
      - install-qvain:/opt/fairdata
      - user-qvain:/home/qvain
    cap_add:
      - ALL 

  etsin.csc.local:
    image: etsin:1
    domainname: csc.local
    hostname: etsin
    build:
      context: ./etsin
      args:
        etsin_ops_branch: "${ETSIN_OPS_BRANCH:-master}"
        etsin_finder_branch: "${ETSIN_FINDER_BRANCH:-test}"
        etsin_finder_search_branch: "${ETSIN_FINDER_SEARCH_BRANCH:-test}"
    privileged: true
    depends_on:
      - cscdevbase
      - simplesaml.csc.local
      - metax.csc.local
      - download.csc.local
      - matomo.csc.local
    ports:
      - "${ETSIN_PORT_HTTPS:-443}:443"
      - "${ETSIN_PORT_HTTP:-80}:80"
    cap_add:
      - ALL 
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-etsin:/code
      - user-etsin:/home/etsin-user

  ida.csc.local:
    image: ida:1
    domainname: csc.local
    hostname: ida
    build:
      context: ./ida
      args:
        ida2_branch: "${IDA2_BRANCH:-master}"
        ida2_command_line_tools_branch: "${IDA2_COMMAND_LINE_TOOLS_BRANCH:-master}"
    privileged: true
    depends_on:
      - cscdevbase
      - rabbitmq-ida.csc.local
      - metax.csc.local
    ports:
      - "${IDA_PORT_ALT_HTTPS:-5433}:4433"
      - "${IDA_PORT_HTTPS:-443}:443"
      - "${IDA_PORT_HTTP:-80}:80"
    cap_add:
      - ALL
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-ida:/code

  fairdata.csc.local:
    image: fairdata:1
    build:
      context: ./fairdata
    domainname: csc.local
    hostname: fairdata
    privileged: true
    depends_on:
      - cscdevbase
      - metax.csc.local
      - qvain.csc.local
      - etsin.csc.local
      - ida.csc.local
    ports:
      - "443:443"
      - "80:80"
    cap_add:
      - ALL 
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - code-fairdata:/code

  matomo-db.csc.local:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo-db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: matomo_database
      MYSQL_USER: matomo

  matomo.csc.local:
    image: fairmatomo:1
    build:
      context: ./matomo
    domainname: csc.local
    hostname: matomo
    depends_on:
      - matomo-db.csc.local
    volumes:
      - matomo:/var/www/html
    environment:
      VIRTUAL_HOST:
      MATOMO_DATABASE_HOST: matomo-db.csc.local
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: changeme
      MATOMO_DATABASE_DBNAME: matomo_database