<?php
$CONFIG = array (
  'instanceid' => 'REPLACE_INSTANCEID',
  'passwordsalt' => 'REPLACE_PASSWORDSALT',
  'secret' => 'REPLACE_SECRET',
  'trusted_domains' => array (
    0 => 'localhost',
    1 => '127.0.0.1',
    2 => 'ida.csc.local',
  ),
  'datadirectory' => '/mnt/storage_vol01/ida',
  'overwrite.cli.url' => 'https://localhost',
  'dbtype' => 'pgsql',
  'version' => '16.0.3.0',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'nextcloud',
  'installed' => true,
  'htaccess.RewriteBase' => '/',
  'theme' => 'ida',
  'knowledgebaseenabled' => false,
  'has_internet_connection' => false,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'updatechecker' => false,
  'updater.release.channel' => 'invalid',
  'updater.server.url' => "https://127.0.0.1/updater",
  'connectivity_check_domains' => array(
    'ida.csc.local',
  ),
  'appstoreenabled' => false,
  'enable_previews' => false,
  'logfile' => '/mnt/storage_vol01/log/nextcloud.log',
  'loglevel' => 0,
  'cron_log' => true,
  'maintenance' => false,
  'integrity.check.disabled' => true,
  'filelocking.enabled' => false,
  'memcache.distributed' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
    'host' => '127.0.0.1',
    'port' => 6379,
    'dbindex' => 0,
    'timeout' => 0.0,
  ),
  'ida' => array (
    'IDA_ENVIRONMENT' => 'TEST',
    'PROJECT_USER_PASS' => 'test',
    'BATCH_ACTION_TOKEN' => 'test',
    'RABBIT_HOST' => 'rabbitmq-ida.csc.local',
    'RABBIT_PORT' => 5672,
    'RABBIT_VHOST' => 'ida-vhost',
    'RABBIT_WORKER_USER' => 'ida-worker',
    'RABBIT_WORKER_PASS' => 'changeme',
    'URL_BASE_FILE' => 'https://ida.csc.local/remote.php/webdav',
    'URL_BASE_SHARE' => 'https://ida.csc.local/ocs/v1.php/apps/files_sharing/api/v1/shares',
    'URL_BASE_GROUP' => 'https://ida.csc.local/ocs/v1.php/cloud/groups',
    'SIMULATE_AGENTS' => false,
  ),
);
