#########################################################
# License: MIT
#
# Author(s):
#      Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# (C) 2019 Copyright CSC - IT Center for Science Ltd.
# All Rights Reserved.
#########################################################
version: "3.7"
volumes:
  metaxdata:
    name: fairdata-dev-docker_metaxdata
    external: true
  qvaindata:
    name: fairdata-dev-docker_qvaindata
    external: true
  elasticsearchdata:
    name: fairdata-dev-docker_elasticsearchdata
    external: true
  code-etsin:
    name: fairdata-dev-docker_code-etsin
    external: true
  code-qvain:
    name: fairdata-dev-docker_code-qvain
    external: true
  code-metax:
    name: fairdata-dev-docker_code-metax
    external: true
  code-download:
    name: fairdata-dev-docker_code-download
    external: true
  code-fairdata:
    name: fairdata-dev-docker_code-fairdata
    external: true
  code-simplesaml:
    name: fairdata-dev-docker_code-simplesaml
    external: true
  install-qvain:
    name: fairdata-dev-docker_install-qvain
    external: true
  install-metax:
    name: fairdata-dev-docker_install-metax
    external: true
  install-download:
    name: fairdata-dev-docker_install-download
    external: true
  user-qvain:
    name: fairdata-dev-docker_user-qvain
    external: true
  user-metax:
    name: fairdata-dev-docker_user-metax
    external: true
  idadata:
    name: fairdata-dev-docker_idadata
    external: true
  code-ida:
    name: fairdata-dev-docker_code-ida
    external: true


services:
  fairdata-dev-container:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh-localhost:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - install-download:/workspace/install/download
      - install-qvain:/workspace/install/qvain
      - install-metax:/workspace/install/metax
      - user-metax:/workspace/user/metax
      - user-qvain:/workspace/user/qvain
      - code-download:/workspace/code/download
      - code-qvain:/workspace/code/qvain
      - code-metax:/workspace/code/metax
      - code-etsin:/workspace/code/etsin
      - code-fairdata:/workspace/code/fairdata
      - code-simplesaml:/workspace/code/simplesaml
      - code-ida:/workspace/code/ida
      - metaxdata:/workspace/data/metax
      - qvaindata:/workspace/data/qvain
      - idadata:/workspace/data/ida
      - elasticsearchdata:/workspace/data/elasticsearch
