#########################################################
# This file contains the Docker image configuration
# which will enable us to run the Matomo service
# inside a container for development and testing purposes.
#
# Author(s):
#      Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# (C) 2020 Copyright CSC - IT Center for Science Ltd.
# All Rights Reserved.
#########################################################

FROM matomo
ADD config.ini.php /var/www/html/config/
